name: Build Application
on: [push, workflow_dispatch]
jobs:
    build:
        name: Build application
        runs-on: ubuntu_latest
        steps:
            - name: Checkout code
              run: echo "Hello World"

        